// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk0flenczL_5Oh7KHfyPushBkY7iK73Ho',
    appId: '1:512388339994:web:b8ffd908d0db8f17ee74a3',
    messagingSenderId: '512388339994',
    projectId: 'nabd-1fb50',
    authDomain: 'nabd-1fb50.firebaseapp.com',
    storageBucket: 'nabd-1fb50.appspot.com',
    measurementId: 'G-5RV3TL3TVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByYe-oWjkxqd-oRsh2PRfevTmsKawDHBY',
    appId: '1:512388339994:android:741a694108738023ee74a3',
    messagingSenderId: '512388339994',
    projectId: 'nabd-1fb50',
    storageBucket: 'nabd-1fb50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-BEJ5G0ihvRFmNUjhJvxVUpJKcZhiZ0Y',
    appId: '1:512388339994:ios:5cd3caeab886c1afee74a3',
    messagingSenderId: '512388339994',
    projectId: 'nabd-1fb50',
    storageBucket: 'nabd-1fb50.appspot.com',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-BEJ5G0ihvRFmNUjhJvxVUpJKcZhiZ0Y',
    appId: '1:512388339994:ios:880e04696d9bba10ee74a3',
    messagingSenderId: '512388339994',
    projectId: 'nabd-1fb50',
    storageBucket: 'nabd-1fb50.appspot.com',
    iosBundleId: 'com.example.pulse.RunnerTests',
  );
}
